name: dhbw-mannheim-schedule # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: display the DHBW Mannheim schedule in CLI # 79 char long summary
description: |
  display the DHBW Mannheim schedule in CLI.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  dhbw-mannheim-schedule:
    plugin: cmake
    source: https://github.com/tobiscripter/dhbwtinf20it1schedule.git
    build-packages:
    - cmake
    - libcurl4-openssl-dev
    stage-packages:
    - libasn1-8-heimdal
    - libcurl4
    - libgssapi3-heimdal
    - libhcrypto4-heimdal
    - libheimbase1-heimdal
    - libheimntlm0-heimdal
    - libhx509-5-heimdal
    - libkrb5-26-heimdal
    - libldap-2.4-2
    - libnghttp2-14
    - libpsl5
    - libroken18-heimdal
    - librtmp1
    - libsasl2-2
    - libwind0-heimdal

apps:
  dhbw-mannheim-schedule:
    command: schedule
    plugs: [network]